# Chave do projeto gerada no SonarCloud ao criar o projeto
sonar.projectKey=gugags6_desafio-ci
sonar.organization=gugags6

# Diretórios que contêm os fontes (o código de produção)
sonar.sources=src

# Diretórios que contêm os testes unitários
sonar.tests=tests

# Arquivo com a cobertura de código gerado pelo Jest (necessário configurar Jest para lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding do projeto
sonar.sourceEncoding=UTF-8
